// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2KyWmtShB1Q5q8c31o1em-ZSd-loaCf0',
    appId: '1:259298175512:android:7670af24990215a8dd716d',
    messagingSenderId: '259298175512',
    projectId: 'explorify24-f06aa',
    databaseURL: 'https://explorify24-f06aa-default-rtdb.firebaseio.com',
    storageBucket: 'explorify24-f06aa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbTYuAWcqnPmXdAq1u9f3lxzYODBnW1io',
    appId: '1:259298175512:ios:d618f86cf7fc4f4ddd716d',
    messagingSenderId: '259298175512',
    projectId: 'explorify24-f06aa',
    databaseURL: 'https://explorify24-f06aa-default-rtdb.firebaseio.com',
    storageBucket: 'explorify24-f06aa.appspot.com',
    iosClientId: '259298175512-nargji231otmtm9qg05l72o7ci3a0t5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.explorify',
  );
}
